application: musubio-player
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: site/index.html
  upload: site/index.html
  secure: always

- url: /(.*)
  static_files: site/\1
  upload: (.*)
  secure: always
